package hack.leetcode.dev;

/*
 * Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.
 */
public class FindTheDifference {
	public char findTheDifference(String s, String t) {
		int[] count = new int[26];

		for (char c : s.toCharArray()) {
			count[c - 'a']++;
		}

		for (char c : t.toCharArray()) {
			count[c - 'a']--;
		}

		for (int i = 0; i < count.length; i++) {
			if (count[i] != 0) {
				return (char) ('a' + i);
			}
		}
		
		return ' ';
	}
}
